### ISSUE TITLE
임대사이트_서류스케줄_등기보는 곳(매달,분기)

### ISSUE THREAD

**Issue by somekim** [somekim/singlesurfer#2]
매월(4대보험,국세,지방세,납입증명서)

> 의왕시(기성청구서)
김해시(기성청구서):: 기존분: 2번도장 증설분: 원인감
인천시(기성청구서):: 각 구별, 남구는 20일날

분기

> 안양시(기성청구서)
수원시(기성청구서)
용인시(기성청구서)
증평군(기성청구서)
구리시(기성청구서) 
서울시(기성청구서):: 부분준공신고서 *나라장터

**Comment by kwonyoungwoo** [comment]
인천시 구별 매월 청구

> 인천시동구(기성청구서):: 원인감
인천시중구(기성청구서):: 2번도장
인천시계양구(기성청구서):: 2번도장
인천시연수구(기성청구서):: 2번도장
인천시강화도(기성청구서):: 2번도장
인천시남구(기성청구서):: 원인감_20일

> 구별초과금내역서 처리중_임차장
